include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    directives_ordering: true
    unnecessary_final: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    constant_identifier_names: false

