name: albums
description: 1001 albums you must hear before you die
# app name:
# Open AndroidManifest.xml (located at android/app/src/main)
# <application android:label="App Name" ...> // Your app name here

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# d https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  csv: ^6.0.0
  path_provider: ^2.1.5
  draggable_scrollbar: ^0.1.0
  shared_preferences: ^2.3.4
  alphanum_comparator: ^2.0.2
  flutter_rating: 2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - secrets.json
    - assets/albums.csv
    - images/ic_album.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
